List<String> expenseCategories = [
  'Food',
  'Groceries',
  'Transport',
  'Entertainment',
  'Bills',
  'Shopping / Clothing',
  'Health / Medical',
  'Education / Learning',
  'Travel / Vacation',
  'Subscriptions',
  'Gifts / Charity',
  'Home / Maintenance',
  'Insurance',
  'Savings / Investment',
  'Others',
];

List<String> incomeCategories = [
  'Salary',
  'Freelance / Contract',
  'Business',
  'Bonus',
  'Commission',
  'Investment Returns',
  'Rental Income',
  'Side Hustle / Gig',
  'Dividends',
  'Interest',
  'Gifts Received',
  'Refunds / Reimbursements',
  'Sales / Selling Items',
  'Pension',
  'Government Benefits',
  'Cashback / Rewards',
  'Royalties',
  'Grants / Scholarships',
  'Tax Refund',
  'Others',
];
